apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'html-openshift-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:1.20-ubi7'
        namespace: openshift
  source:
    type: Git
    git:
      uri: 'https://github.com/lukavukadin/zli_m109.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: html-openshift-app-generic-webhook-secret
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial