apiVersion: v1
kind: Secret
metadata:
  name: html-openshift-app-generic-webhook-secret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
type: Opaque
data:
  WebHookSecretKey: bHVrYXMta2V5